### ISSUE TITLE
Vaccination problems

### ISSUE THREAD

**Issue by HappyFr1tz** [marlon360/rki-covid-api#154] opened 2021-04-08 17:20 UTC
As of today, an error message appears when trying to access https://api.corona-zahlen.org/vaccinations.
> {"error":{"message":"An error occurred.","details":"Cannot read property 'includes' of undefined","stack":"TypeError: Cannot read property 'includes' of undefined\n at Object. (/usr/src/app/src/data-requests/vaccination.ts:205:50)\n at Generator.next ()\n at fulfilled (/usr/src/app/dist/data-requests/vaccination.js:5:58)\n at runMicrotasks ()\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}}

**Comment by marlon360** [comment] 2021-04-08 17:25
Duplicate of #153

**Closed as completed** 2021-04-08 17:25 UTC
Labels: duplicate
