### ISSUE TITLE
Missing districts in cases

### ISSUE THREAD

**Issue by pitrade** [marlon360/rki-covid-api#284] opened 2021-09-25 01:50 UTC
Depending on the days parameter of the Endpoint /districts/history/cases/:days
the result misses some states and their districts.

**Examples**
- days = 7: result contains only districts with ags from 01... to 05...
- days = 14: result contains all districts
- days = 28: result contains only districts with ags from 01... to 08...
- days = 365: result contains all districts

Also: Is the history limited to 36 days?

**Comment by Rubber1Duck** [comment] 2021-09-26 22:12
Unfortunately, I cannot understand your problem. With both 7 and 28 days, all AGS are included in my list!
Is that Issue still there? when not please close this issue!

And yes the history is limited to 36 days because there is a limit of datasets that can be requested from the used database! I dont know the axactly count by i meen 3000 ....... if you wish more than 36 days you have to request the districs seperatly ....

eg: /districts/05119/history/cases/300

**Comment by pitrade** [comment] 2021-09-30 12:15
Thanks for your explanation. I can not check if the issue is still there bc I get HTTP 502 on https://api.corona-zahlen.org/districts/history/cases/7

**Comment by Rubber1Duck** [comment] 2021-09-30 16:04
Maybe thats a Proxy error?!Am 30.09.2021 14:16 schrieb pitrade ***@***.***>:
Thanks for your explanation. I can not check if the issue is still there bc I get HTTP 502 on https://api.corona-zahlen.org/districts/history/cases/7

**Comment by Rubber1Duck** [comment] 2021-11-10 10:29
@pitrade i think this issue can be closed!?

**Comment by Rubber1Duck** [comment] 2022-02-22 18:19
no further replies for 3 months .... will close this issue

**Closed as completed by Rubber1Duck** 2022-02-22 18:19 UTC
