### ISSUE TITLE
Wrong number of death from /germany/history/deaths/:days

### ISSUE THREAD

**Issue by CarstenGorkow** [marlon360/rki-covid-api#76] opened 2021-01-25 14:23 UTC
Hi
The number of death from histroy data is not correct. See image.
For 24.1.21 the number must be  349 but is 4.
For 23.1.21 the number must be  879 but is 10. (See daily report from RKI https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Jan_2021/2021-01-24-de.pdf?__blob=publicationFile)

In the /germany reqeust the number is right..

Regards Carsten

![Bild_2021-01-25_151958](https://user-images.githubusercontent.com/25474143/105717749-ca25d000-5f20-11eb-9302-476be6d76de4.png)

**Comment by marlon360** [comment] 2021-01-25 14:28
Duplicate of #64

**Comment by marlon360** [comment] 2021-01-25 14:29
Hello @CarstenGorkow 

The number of new deaths in (/germany) does not reflect the new deaths on a particular day (/history). The new deaths are all new deaths in the last days that got registered by the RKI yesterday. There are always delays between the health departments and the RKI.

**Closed as completed by marlon360** 2021-01-25 14:29 UTC
Labels: duplicate
