### ISSUE TITLE
RKI API issue

### ISSUE THREAD

**Issue by JonathanN1203** [marlon360/rki-covid-api#341] opened 2021-11-24 07:46 UTC
Hi,

currently I get the error **There is a problem with the official RKI API** with the following endpoints:
/districts/09175/history/cases
/states/BY/history/incidence
/germany/history/incidence
Have we to wait or can we change something

**Comment by Rubber1Duck** [comment] 2021-11-24 08:03
Same here on my self hosted server.
as the errormessage said .... There is a problem with the official RKI API.
Database looks for a access token which is usually not necessary. this is not the first time this error occurs.
As you can see here

![database](https://user-images.githubusercontent.com/6493772/143198142-d5870107-ab9a-4887-87fa-b87fb02ce30a.png)

the database is still updating (and i think it is blocked for that time!)
we have to wait, this can take a few hours .............. and if it is not done we have to look for another solution

**Comment by JonathanN1203** [comment] 2021-11-24 08:04
ok, thanks for the info. Which page do you use on the screenshot?

**Comment by Rubber1Duck** [comment] 2021-11-24 08:07
[https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/rki_service_status_v/FeatureServer/0/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=html&token=](https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/rki_service_status_v/FeatureServer/0/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=html&token=)

**Comment by Shineson1001** [comment] 2021-11-24 09:04
Hi,
same problem:
![grafik](https://user-images.githubusercontent.com/22273771/143207028-3acdb72d-393e-4053-920d-2359fb52e6c7.png)

URL:
`https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall IN(1,-1)&objectIds=&time=&resultType=standard&outFields=AnzahlFall,MeldeDatum,IdBundeland&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdBundesland&groupByFieldsForStatistics=IdBundesland&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlFall\",\"outStatisticFieldName\":\"cases\"},{\"statisticType\":\"max\",\"onStatisticField\":\"MeldeDatum\",\"outStatisticFieldName\":\"date\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token=`

Result:
![grafik](https://user-images.githubusercontent.com/22273771/143207267-d255af07-ac78-4bc5-a7c8-ea4ad9fe7b3b.png)



Or try this page: https://api.corona-zahlen.org/states/NW

![grafik](https://user-images.githubusercontent.com/22273771/143209560-6a8f561d-ddcd-4218-b5ff-d1d9f10be4ed.png)

**Comment by Rubber1Duck** [comment] 2021-11-24 09:40
again, please be patient, this bug will be fixed in a while! I'm sure arcgis is working hard on it.
this is not a bug in this API!

**Closed as completed** 2021-11-24 10:21 UTC
