### ISSUE TITLE
Wrong number of cases for Germany

### ISSUE THREAD

**Issue by hajo62** [marlon360/rki-covid-api#342] opened 2021-11-24 08:01 UTC
[New Cases for Germany](https://api.corona-zahlen.org/germany) should be 66.884 as shown [here](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html), but the API gives 194.951.
<img width="273" alt="grafik" src="https://user-images.githubusercontent.com/15800980/143197833-73f742b5-b45b-4f04-94ae-ea920ca2292e.png">
<img width="491" alt="grafik" src="https://user-images.githubusercontent.com/15800980/143198075-765414c7-beff-4eca-8196-349b6b9eed4a.png">

**Comment by Rubber1Duck** [comment] 2021-11-24 08:14
when did you pull this data?
at the moment there is an error message.
I assume that it is related to the fact that the database of the rki was inconsistent and is therefore now also blocked!
see #341

**Comment by hajo62** [comment] 2021-11-24 08:19
Maybe five minutes before I submitted the issue. But after #341 .
Now the link above shows something with **Token required**...

**Comment by Rubber1Duck** [comment] 2021-11-24 08:20
lets wait ........... maybe a few hours!

**Comment by Toni-99** [comment] 2021-11-24 09:04
Now there is an error. 

BTW: Districts Endpoint returns an error as well.

<img width="1671" alt="grafik" src="https://user-images.githubusercontent.com/71496013/143207377-7bf2b763-1ed8-45b0-aca2-c200dbc1912b.png">


<img width="1671" alt="grafik" src="https://user-images.githubusercontent.com/71496013/143207272-c841ad0e-f787-47e5-9955-8f25447e49bf.png">

**Comment by Rubber1Duck** [comment] 2021-11-24 10:10
again, please be patient, this bug will be fixed in a while! I'm sure arcgis is working hard on it.
this is not a bug in this API!

**Comment by Rubber1Duck** [comment] 2021-11-24 17:27
it seems all is running again ........... lets close this issue

**Closed as completed by Rubber1Duck** 2021-11-24 17:27 UTC
